
# Get post by ID
GET http://localhost:3000/api/posts/569bb5e6-abea-4e0c-acc0-1e8d8e14d384 HTTP/1.1

###

# Test

GET http://localhost:3000/api/posts?limit=2&page=2

###

# Create post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "authorId": "66bb4569d589a96532f9715c",
  "isDraft": true,
  "type": "VIDEO",
  "tags": ["cats"],
  "videoPost": {
    "title": "test video534345567865767867876786",
    "link": "https://vk.ru/video-220060683_456241083"
  }
}
